# Generated by Django 3.0 on 2022-02-22 03:23

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('skills', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='skills',
            name='user_obj',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='user_obj', to=settings.AUTH_USER_MODEL),
        ),
    ]
